export const ADD_TO_CART="ADD_TO_CART"
export const INC_CART="INC_CART"
export const DEC_CART="DEC_CART"
export const DELETE_ITEM_FROM_CART="DELETE_ITEM_FROM_CART"
export const LOADING_CART="LOADING_CART"
export const ERROR_IN_CART="ERROR_IN_CART"
export const CLEAR_CART="CLEAR_CART"
export const GET_CART="GET_CART"